on:
  push:
    tags:
      - 'v*'

name: Create Build & Release

jobs:
  Publish:
    name: PSAke Publish Task
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Dependencies from PSGallery
        shell: pwsh
        run: |
            Set-PSRepository PSGallery -InstallationPolicy Trusted
            Install-Module Psake
      - name: Invoke PSAke
        shell: pwsh
        run: Invoke-psake -taskList 'Build'
      - name: Create Release
        uses: ncipollo/release-action@v1